; =============================================================================
; Lib: UiElementCatalog.ahk
; Logical UIA controls the scripts already look up, grouped by cheat-sheet key.
; One row per control. Fallback chains stay in the finder that calls
; UiElements_TrySaved. Section defaults to appKey; the three companions use
; the AiCompanionButtons section names.
; =============================================================================

UiElementCatalog_Entry(appKey, id, label, source, kind := "button", section := "") {
    if (section = "")
        section := appKey
    return {
        appKey: appKey,
        id: id,
        label: label,
        source: source,
        kind: kind,
        section: section
    }
}

UiElementCatalog_All() {
    static rows := ""
    if (IsObject(rows))
        return rows
    e := UiElementCatalog_Entry
    rows := [
        e.Call("Gemini", "NewChat", "New chat", "Lib/AiCompanionModels.ahk", "button", "Gemini"),
        e.Call("Gemini", "Menu", "Main menu", "Shift keys/gemini_chrome_01.ahk", "button", "Gemini"),
        e.Call("Gemini", "Search", "Search", "Shift keys/gemini_chrome_01.ahk", "button", "Gemini"),
        e.Call("Gemini", "Send", "Send", "Utils/gemini_paste_helpers.ahk", "button", "Gemini"),
        e.Call("Gemini", "Prompt", "Prompt field", "Shift keys/gemini_chrome_02.ahk", "edit", "Gemini"),
        e.Call("Gemini", "Tools", "Tools", "Shift keys/gemini_chrome_02.ahk", "button", "Gemini"),
        e.Call("Gemini", "Upload", "Open upload file menu", "Utils/helpers_timing_gemini.ahk", "button", "Gemini"),
        e.Call("Gemini", "CreateImage", "Create image", "Shift keys/gemini_chrome_02.ahk", "any", "Gemini"),
        e.Call("Gemini", "DeepResearch", "Deep research", "Shift keys/gemini_chrome_02.ahk", "any", "Gemini"),
        e.Call("Gemini", "MoreTools", "More tools", "Shift keys/gemini_chrome_02.ahk", "any", "Gemini"),
        e.Call("Gemini", "Stop", "Stop response", "Utils/gemini_paste_helpers.ahk", "button", "Gemini"),
        e.Call("Gemini", "Expand", "Expand input", "Shift keys/gemini_chrome_02.ahk", "button", "Gemini"),
        e.Call("Gemini", "TextToSpeech", "Text to speech", "Shift keys/gemini_chrome_02.ahk", "any", "Gemini"),
        e.Call("Gemini", "MoreOptions", "Show more options", "Shift keys/gemini_chrome_02.ahk", "button", "Gemini"),
        e.Call("Gemini", "Listen", "Listen", "Gemini/config_constants.ahk", "any", "Gemini"),
        e.Call("Gemini", "Copy", "Copy", "Shift keys/gemini_chrome_02.ahk", "button", "Gemini"),
        e.Call("Gemini", "ModePicker", "Open mode picker", "Utils/gemini_mode_picker.ahk", "button", "Gemini"),
        e.Call("Gemini Enterprise", "NewChat", "New chat", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Menu", "Menu", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Search", "Search", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Send", "Submit", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Prompt", "Prompt field", "Lib/GeminiEnterprise.ahk", "edit", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Tools", "Select tools", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "CreateImages", "Create images", "Lib/GeminiEnterprise.ahk", "any",
            "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "DeepResearch", "Deep research", "Lib/GeminiEnterprise.ahk", "any",
            "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "ChooseModel", "Choose model", "Lib/GeminiEnterprise.ahk", "button",
            "GeminiEnterprise"),
        e.Call("Gemini Enterprise", "Stop", "Stop", "Lib/GeminiEnterprise.ahk", "button", "GeminiEnterprise"),
        e.Call("Copilot Web", "NewChat", "New chat", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Menu", "Navigation drawer", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Search", "Search", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Send", "Send", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Prompt", "Composer", "Lib/CopilotWeb.ahk", "edit", "CopilotWeb"),
        e.Call("Copilot Web", "Stop", "Stop generating", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Expand", "Expand composer", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "ModelSelector", "Model selector", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Sources", "Sources", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "AddCapabilities", "Add capabilities", "Lib/CopilotWeb.ahk", "any", "CopilotWeb"),
        e.Call("Copilot Web", "GenerateImage", "Generate an image", "Lib/CopilotWeb.ahk", "any", "CopilotWeb"),
        e.Call("Copilot Web", "Research", "Research a topic", "Lib/CopilotWeb.ahk", "any", "CopilotWeb"),
        e.Call("Copilot Web", "MoreOptions", "More options", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "ReadAloud", "Read aloud", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "ReadAloudMenu", "Read aloud menu", "Lib/CopilotWeb.ahk", "any", "CopilotWeb"),
        e.Call("Copilot Web", "Pause", "Pause", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Copilot Web", "Resume", "Resume", "Lib/CopilotWeb.ahk", "button", "CopilotWeb"),
        e.Call("Power BI", "HomeTab", "Home tab", "Shift keys/hotif_powerbi.ahk", "any"),
        e.Call("Power BI", "GetData", "Get data", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Transform", "Transform data", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "ReportView", "Report view", "Shift keys/hotif_powerbi.ahk", "any"),
        e.Call("Power BI", "TableView", "Table view", "Shift keys/hotif_powerbi.ahk", "any"),
        e.Call("Power BI", "ModelView", "Model view", "Shift keys/hotif_powerbi.ahk", "any"),
        e.Call("Power BI", "BuildVisual", "Build visual", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "FormatVisual", "Format visual", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Search", "Search field", "Shift keys/hotif_powerbi.ahk", "edit"),
        e.Call("Power BI", "Confirm", "OK / Confirm", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Cancel", "Cancel", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "AllPages", "All pages", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "NewPage", "New page", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "NewMeasure", "New measure", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Refresh", "Refresh", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Publish", "Publish", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "BringForward", "Bring forward", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "SendBackward", "Send backward", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Align", "Align", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "FitToPage", "Fit to page", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "FormatPainter", "Format painter", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("Power BI", "Group", "Group", "Shift keys/hotif_powerbi.ahk", "button"),
        e.Call("YouTube", "Search", "Search box", "Shift keys/hotif_youtube.ahk", "edit"),
        e.Call("YouTube", "SearchFilters", "Search filters", "Shift keys/hotif_youtube.ahk", "button"),
        e.Call("YouTube", "Explore", "Explore", "Shift keys/hotif_youtube.ahk", "button"),
        e.Call("FileDialog", "Address", "Address bar", "Shift keys/hotif_file_dialog.ahk", "edit"),
        e.Call("FileDialog", "FileName", "File name", "Shift keys/hotif_file_dialog.ahk", "edit"),
        e.Call("FileDialog", "Open", "Open", "Shift keys/hotif_file_dialog.ahk", "button"),
        e.Call("FileDialog", "Save", "Save", "Shift keys/hotif_file_dialog.ahk", "button"),
        e.Call("FileDialog", "Load", "Load", "Shift keys/hotif_file_dialog.ahk", "button"),
        e.Call("FileDialog", "PdfType", "PDF file type", "Shift keys/hotif_file_dialog.ahk", "any"),
        e.Call("FileDialog", "CsvUtf8", "CSV UTF-8", "Shift keys/hotif_file_dialog.ahk", "any"),
        e.Call("FileDialog", "Cancel", "Cancel", "Shift keys/hotif_file_dialog.ahk", "button"),
        e.Call("FileDialog", "Export", "Export", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("FileDialog", "Home", "Home", "Shift keys/hotif_outlook_main.ahk", "any"),
        e.Call("FileDialog", "Pinned", "Pinned", "Shift keys/hotif_outlook_main.ahk", "any"),
        e.Call("Chrome PDF Viewer", "Download", "Download", "Shift keys/hotif_chrome_pdf.ahk", "button"),
        e.Call("Chrome PDF Viewer", "Present", "Present", "Shift keys/hotif_chrome_pdf.ahk", "any"),
        e.Call("Chrome PDF Viewer", "Fit", "Fit to page", "Shift keys/hotif_chrome_pdf.ahk", "button"),
        e.Call("Chrome PDF Viewer", "Page", "Page number", "Shift keys/hotif_chrome_pdf.ahk", "edit"),
        e.Call("Chrome PDF Viewer", "Thumbnails", "Thumbnails", "Shift keys/hotif_chrome_pdf.ahk", "button"),
        e.Call("Chrome PDF Viewer", "MoreActions", "More actions", "Shift keys/hotif_chrome_pdf.ahk", "button"),
        e.Call("Chrome PDF Viewer", "TwoPage", "Two page", "Shift keys/hotif_chrome_pdf.ahk", "any"),
        e.Call("explorer.exe", "ItemsView", "Items view", "Shift keys/hotif_explorer.ahk", "any"),
        e.Call("explorer.exe", "Back", "Share settings back", "Shift keys/hotif_explorer.ahk", "button"),
        e.Call("explorer.exe", "Home", "Home", "Shift keys/hotif_explorer.ahk", "any"),
        e.Call("explorer.exe", "Pinned", "Pinned", "Shift keys/hotif_explorer.ahk", "any"),
        e.Call("explorer.exe", "CopyLink", "Copy link", "Shift keys/hotif_explorer.ahk", "button"),
        e.Call("explorer.exe", "ShareSettings", "Share settings", "Shift keys/hotif_explorer.ahk", "button"),
        e.Call("explorer.exe", "Apply", "Apply", "Shift keys/hotif_explorer.ahk", "button"),
        e.Call("explorer.exe", "BoschGroup", "People in Bosch Group", "Shift keys/hotif_explorer.ahk", "any"),
        e.Call("TeamsMeeting", "Chat", "Chat", "Shift keys/hotif_teams_meeting.ahk", "button"),
        e.Call("TeamsMeeting", "React", "React", "Shift keys/hotif_teams_meeting.ahk", "button"),
        e.Call("TeamsMeeting", "Join", "Join now", "Shift keys/hotif_teams_meeting.ahk", "button"),
        e.Call("TeamsMeeting", "Audio", "Audio settings", "Shift keys/hotif_teams_meeting.ahk", "button"),
        e.Call("TeamsChat", "Back", "Back", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "Forward", "Forward", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "MoreOptions", "More chat options", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "Detach", "Open in new window", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "Participants", "View and add participants", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "Call", "Call", "Shift keys/hotif_teams_chat.ahk", "button"),
        e.Call("TeamsChat", "QuickViews", "Quick views", "Shift keys/hotif_teams_chat.ahk", "any"),
        e.Call("TeamsChat", "Composer", "Compose box", "Utils/teams_jump_to_chat.ahk", "edit"),
        e.Call("OUTLOOK.EXE", "Mail", "Mail module", "Outlook.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Calendar", "Calendar module", "Outlook.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Reply", "Reply", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "ReplyAll", "Reply all", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Forward", "Forward", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Delete", "Delete", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Archive", "Archive", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "ReadUnread", "Read / Unread", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Categorize", "Categorize", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Move", "Move", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Filter", "Filter", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Sort", "Sort", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "NewEvent", "New event", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Week", "Week", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Month", "Month", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Bcc", "Bcc", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Search", "Search", "Shift keys/outlook_helpers_01.ahk", "edit"),
        e.Call("OUTLOOK.EXE", "Today", "Go to today", "Shift keys/outlook_helpers_01.ahk", "button"),
        e.Call("OUTLOOK.EXE", "PopOut", "Pop Out", "Shift keys/hotif_outlook_main.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Focused", "Focused", "Shift keys/hotif_outlook_main.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Other", "Other", "Shift keys/hotif_outlook_main.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Home", "Home tab", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Inbox", "Inbox", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OUTLOOK.EXE", "ShowNavigation", "Show navigation pane", "Shift keys/outlook_helpers_02.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Accept", "Accept the meeting", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OUTLOOK.EXE", "Follow", "Follow", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OUTLOOK.EXE", "RemoveEvent", "Remove event", "Shift keys/outlook_helpers_02.ahk", "button"),
        e.Call("OUTLOOK.EXE", "MoreOptions", "More options", "Shift keys/outlook_helpers_02.ahk", "button"),
        e.Call("OUTLOOK.EXE", "Tentative", "Tentative", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OUTLOOK.EXE", "RespondWithoutEmail", "Respond without email", "Shift keys/outlook_helpers_02.ahk",
            "any"),
        e.Call("OUTLOOK.EXE", "DeclineSilently", "Decline silently", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OutlookAppointment", "Send", "Send", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Save", "Save", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Back", "Back", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Options", "Options", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Private", "Private", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Scheduler", "Scheduler", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "StartDate", "Start date", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "StartTime", "Start time", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "EndTime", "End time", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "AllDay", "All day", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Title", "Title", "Shift keys/outlook_appointment_hotif_02.ahk", "edit"),
        e.Call("OutlookAppointment", "Required", "Required", "Shift keys/outlook_appointment_hotif_02.ahk", "edit"),
        e.Call("OutlookAppointment", "Location", "Location", "Shift keys/outlook_appointment_hotif_02.ahk", "edit"),
        e.Call("OutlookAppointment", "Today", "Today", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Recurring", "Make recurring", "Shift keys/outlook_appointment_hotif_02.ahk",
            "button"),
        e.Call("OutlookAppointment", "Teams", "Teams meeting", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Series", "Series", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "AddRequired", "Add required attendee",
            "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "AddOptional", "Add optional attendee",
            "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "TimeZone", "Time zone", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "Body", "Body", "Shift keys/outlook_appointment_hotif_01.ahk", "edit"),
        e.Call("OutlookAppointment", "StatusFree", "Free", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "StatusElsewhere", "Working elsewhere",
            "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "StatusTentative", "Tentative", "Shift keys/outlook_appointment_hotif_02.ahk",
            "any"),
        e.Call("OutlookAppointment", "StatusBusy", "Busy", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "StatusOoo", "Out of office", "Shift keys/outlook_appointment_hotif_02.ahk", "any"
        ),
        e.Call("OutlookAppointment", "RemNone", "Don't remind me", "Shift keys/outlook_appointment_hotif_02.ahk", "any"
        ),
        e.Call("OutlookAppointment", "Rem15m", "15 minutes before", "Shift keys/outlook_appointment_hotif_02.ahk",
            "any"),
        e.Call("OutlookAppointment", "Rem1h", "1 hour before", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "Rem12h", "12 hours before", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "Rem1d", "1 day before", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "Rem1w", "1 week before", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "CatBirthday", "Aniversário", "Shift keys/outlook_appointment_hotif_02.ahk", "any"
        ),
        e.Call("OutlookAppointment", "CatImportant", "Importante", "Shift keys/outlook_appointment_hotif_02.ahk", "any"
        ),
        e.Call("OutlookAppointment", "CatPersonal", "Pessoal", "Shift keys/outlook_appointment_hotif_02.ahk", "any"),
        e.Call("OutlookAppointment", "PrevSuggestion", "Previous time suggestion",
            "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "NextSuggestion", "Next time suggestion",
            "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "PrevDay", "Previous day", "Shift keys/outlook_appointment_hotif_02.ahk", "button"
        ),
        e.Call("OutlookAppointment", "NextDay", "Next day", "Shift keys/outlook_appointment_hotif_02.ahk", "button"),
        e.Call("OutlookAppointment", "DateHeader", "Date header", "Shift keys/outlook_appointment_hotif_02.ahk",
            "button"),
        e.Call("OutlookAppointment", "Suggestion1", "Time suggestion 1", "Shift keys/outlook_appointment_hotif_02.ahk",
            "any"),
        e.Call("OutlookAppointment", "Suggestion2", "Time suggestion 2", "Shift keys/outlook_appointment_hotif_02.ahk",
            "any"),
        e.Call("OutlookMessage", "To", "To field", "Utils/email_note_macro.ahk", "edit"),
        e.Call("OutlookMessage", "Subject", "Subject field", "Utils/email_note_macro.ahk", "edit"),
        e.Call("OutlookMessage", "Accept", "Accept the meeting", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OutlookMessage", "Follow", "Follow", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OutlookMessage", "RemoveEvent", "Remove event", "Shift keys/outlook_helpers_02.ahk", "button"),
        e.Call("OutlookMessage", "MoreOptions", "More options", "Shift keys/outlook_helpers_02.ahk", "button"),
        e.Call("OutlookMessage", "Tentative", "Tentative", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OutlookMessage", "RespondWithoutEmail", "Respond without email", "Shift keys/outlook_helpers_02.ahk",
            "any"),
        e.Call("OutlookMessage", "DeclineSilently", "Decline silently", "Shift keys/outlook_helpers_02.ahk", "any"),
        e.Call("OutlookReminder", "DismissAll", "Dismiss all", "Shift keys/hotif_outlook_reminder.ahk", "button"),
        e.Call("OutlookReminder", "Join", "Join Online", "Shift keys/hotif_outlook_reminder.ahk", "button"),
        e.Call("OutlookReminder", "Snooze10m", "Snooze 10 minutes", "Shift keys/hotif_outlook_reminder.ahk", "any"),
        e.Call("OutlookReminder", "Snooze1h", "Snooze 1 hour", "Shift keys/hotif_outlook_reminder.ahk", "any"),
        e.Call("OutlookReminder", "Snooze4h", "Snooze 4 hours", "Shift keys/hotif_outlook_reminder.ahk", "any"),
        e.Call("OutlookReminder", "Snooze1d", "Snooze 1 day", "Shift keys/hotif_outlook_reminder.ahk", "any"),
        e.Call("OutlookReminder", "Snooze1w", "Snooze 1 week", "Shift keys/hotif_outlook_reminder.ahk", "any"),
        e.Call("Gmail", "MarkAsRead", "Mark as read", "Shift keys/hotif_gmail.ahk", "button"),
        e.Call("Gmail", "Select", "Select", "Shift keys/hotif_gmail.ahk", "button"),
        e.Call("Gmail", "Updates", "Updates", "Shift keys/hotif_gmail.ahk", "button"),
        e.Call("Gmail", "Forums", "Forums", "Shift keys/hotif_gmail.ahk", "button"),
        e.Call("Gmail", "Inbox", "Inbox", "Shift keys/hotif_gmail.ahk", "button"),
        e.Call("Gmail", "Compose", "Compose", "Utils/email_note_macro.ahk", "button"),
        e.Call("Gmail", "To", "To field", "Utils/email_note_macro.ahk", "edit"),
        e.Call("Gmail", "Subject", "Subject field", "Utils/email_note_macro.ahk", "edit"),
        e.Call("Google", "Search", "Search box", "Shift keys/hotif_google_search.ahk", "edit"),
        e.Call("Google", "Images", "Images", "Shift keys/hotif_google_search.ahk", "button"),
        e.Call("Google", "FirstResult", "First result", "Utils/google_search_first_result.ahk", "any"),
        e.Call("Google Maps", "MapPane", "Map pane", "Shift keys/hotif_google_maps.ahk", "any"),
        e.Call("Google Maps", "CollapseSide", "Collapse side panel", "Shift keys/hotif_google_maps.ahk", "button"),
        e.Call("Google Maps", "Search", "Search Google Maps", "Shift keys/hotif_google_maps.ahk", "edit"),
        e.Call("WhatsApp", "Search", "Search", "Shift keys/hotif_whatsapp.ahk", "edit"),
        e.Call("WhatsApp", "Archived", "Archived", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("WhatsApp", "Voice", "Record voice message", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("WhatsApp", "SendVoice", "Send / Stop recording", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("WhatsApp", "Unread", "Unread filter", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("WhatsApp", "All", "All chats filter", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("Mercado Livre", "Search", "Search", "Shift keys/predicates_mercado_livre.ahk", "edit"),
        e.Call("Mercado Livre", "Cart", "Cart", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Purchases", "Purchases", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Tomorrow", "Arrives tomorrow", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Full", "Full", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "International", "International", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Local", "Local shipping", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "FreeShipping", "Free shipping", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Next", "Next page", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Prev", "Previous page", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "AddToCart", "Add to cart", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Favorite", "Add to favorites", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Mercado Livre", "Continue", "Continue", "Shift keys/hotif_mercado_livre.ahk", "button"),
        e.Call("Shopee", "Search", "Search", "Shift keys/predicates_shopee.ahk", "edit"),
        e.Call("Shopee", "Cart", "Cart", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "Purchases", "Purchases", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "PriceMin", "Minimum price", "Shift keys/hotif_shopee.ahk", "edit"),
        e.Call("Shopee", "PriceMax", "Maximum price", "Shift keys/hotif_shopee.ahk", "edit"),
        e.Call("Shopee", "FastDelivery", "Fast delivery", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "Discount", "Discounted products", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "International", "International", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "National", "National shipping", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "FreeShipping", "Free shipping", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "Sort", "Sort", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "AddToCart", "Add to cart", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "Favorite", "Favorite", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Shopee", "Continue", "Continue", "Shift keys/hotif_shopee.ahk", "button"),
        e.Call("Wikipedia", "Search", "Search", "Shift keys/hotif_wikipedia.ahk", "edit"),
        e.Call("Wikipedia", "SearchToggle", "Search link", "Shift keys/hotif_wikipedia.ahk", "button"),
        e.Call("Mobills", "Open", "Open transaction", "Shift keys/mobills_pagination.ahk", "button"),
        e.Call("Mobills", "PagerNext", "Next month", "Shift keys/mobills_pagination.ahk", "button"),
        e.Call("Mobills", "PagerPrev", "Previous month", "Shift keys/mobills_pagination.ahk", "button"),
        e.Call("Mobills", "Dashboard", "Dashboard", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "Accounts", "Accounts", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "Transactions", "Transactions", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "CreditCards", "Credit cards", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "Budgets", "Budgets", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "Reports", "Reports", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Mobills", "MoreOptions", "More options", "Shift keys/hotif_mobills.ahk", "button"),
        e.Call("Cursor.exe", "Composer", "Composer input", "Shift keys/hotif_editor_01.ahk", "edit"),
        e.Call("Cursor.exe", "Sidebar", "Primary side bar", "Shift keys/cursor_predicates.ahk", "button"),
        e.Call("Cursor.exe", "HidePanel", "Hide panel", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Cursor.exe", "CommitInput", "Commit message", "Shift keys/hotif_editor_02.ahk", "edit"),
        e.Call("Cursor.exe", "Pull", "Pull", "Shift keys/cursor_predicates.ahk", "button"),
        e.Call("Cursor.exe", "SyncChanges", "Sync Changes", "Shift keys/cursor_predicates.ahk", "any"),
        e.Call("Cursor.exe", "ReviewNext", "Review next file", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Cursor.exe", "GenerateCommit", "Generate commit message", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("Cursor.exe", "GoBack", "Go Back", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Cursor.exe", "PickModel", "Pick Model", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Cursor.exe", "Send", "Send", "Utils/cursor_composer_focus.ahk", "button"),
        e.Call("Cursor.exe", "ToggleAiPane", "Toggle AI Pane", "Utils/cursor_composer_focus.ahk", "any"),
        e.Call("Code.exe", "HidePanel", "Hide panel", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Code.exe", "CommitInput", "Commit message", "Shift keys/hotif_editor_02.ahk", "edit"),
        e.Call("Code.exe", "Pull", "Pull", "Shift keys/cursor_predicates.ahk", "button"),
        e.Call("Code.exe", "SyncChanges", "Sync Changes", "Shift keys/cursor_predicates.ahk", "any"),
        e.Call("Code.exe", "GenerateCommit", "Generate commit message", "Shift keys/hotif_whatsapp.ahk", "button"),
        e.Call("Code.exe", "GoBack", "Go Back", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Code.exe", "PickModel", "Pick Model", "Shift keys/hotif_editor_02.ahk", "button"),
        e.Call("Code.exe", "Send", "Send", "Utils/cursor_composer_focus.ahk", "button"),
        e.Call("Command Palette", "EditFavorite", "Edit favorite", "Shift keys/command_palette_helpers.ahk", "any"),
        e.Call("Settings", "InputVolume", "Input volume", "Shift keys/hotif_settings.ahk", "any"),
        e.Call("EXCEL.EXE", "EnableEditing", "Enable Editing", "Shift keys/hotif_excel_mspaint.ahk", "button"),
        e.Call("EXCEL.EXE", "FromTextCsv", "From Text/CSV", "Shift keys/hotif_excel_mspaint.ahk", "button"),
        e.Call("EXCEL.EXE", "QueriesClose", "Close queries pane", "Shift keys/hotif_file_dialog.ahk", "any"),
        e.Call("ClipAngel.exe", "Filter", "Type filter", "Shift keys/hotif_clipangel.ahk", "edit"),
        e.Call("ClipAngel.exe", "Clip", "Clip menu", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "List", "List menu", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "Paste", "Paste", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "PasteFile", "Paste file", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "ImportClips", "Import clips", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "ShowAllMarks", "Show all marks", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "ShowOnlyFavorite", "Show only favorite", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("ClipAngel.exe", "MarkFavorite", "Mark favorite", "Utils/clip_angel_favorite.ahk", "any"),
        e.Call("Miro", "CloseSidebar", "Close sidebar", "Shift keys/hotif_miro.ahk", "button"),
        e.Call("Spotify.exe", "Connect", "Connect to a device", "Shift keys/hotif_spotify.ahk", "button"),
        e.Call("Spotify.exe", "OpenLibrary", "Open Your Library", "Shift keys/hotif_spotify.ahk", "button"),
        e.Call("Spotify.exe", "ExpandLibrary", "Expand Your Library", "Shift keys/hotif_spotify.ahk", "button"),
        e.Call("Spotify.exe", "Download", "Download", "Shift keys/hotif_spotify.ahk", "button"),
        e.Call("Spotify.exe", "Office", "Office", "Shift keys/hotif_spotify.ahk", "button"),
        e.Call("Google Keep", "MainMenu", "Main menu", "Shift keys/hotif_google_keep.ahk", "button"),
        e.Call("Settle Up", "Add", "Add transaction", "Shift keys/hotif_settleup.ahk", "button"),
        e.Call("Settle Up", "NewExpense", "New expense", "Shift keys/hotif_settleup.ahk", "any"),
        e.Call("Settle Up", "Name", "Expense name", "Shift keys/hotif_settleup.ahk", "edit"),
        e.Call("Settle Up", "Amount", "Amount", "Shift keys/hotif_settleup.ahk", "edit"),
        e.Call("ChatGPT", "Sidebar", "Sidebar", "Shift keys/hotif_chatgpt.ahk", "button"),
        e.Call("ChatGPT", "Stop", "Stop streaming", "Shift keys/chatgpt_loading_helpers.ahk", "button"),
        e.Call("ChatGPT", "CloseSidebar", "Close sidebar", "Shift keys/hotif_chrome_general.ahk", "button"),
        e.Call("ChatGPT", "YourChats", "Your chats", "Shift keys/hotif_chrome_general.ahk", "button"),
        e.Call("UIATreeInspector", "Refresh", "Refresh list", "Shift keys/hotif_uia_tree.ahk", "button"),
        e.Call("UIATreeInspector", "Filter", "Filter", "Shift keys/hotif_uia_tree.ahk", "any"),
        e.Call("handy.exe", "General", "General", "Utils/handy_uia_helpers.ahk", "any"),
        e.Call("handy.exe", "Language", "Language", "Utils/handy_uia_helpers.ahk", "button"),
        e.Call("handy.exe", "Model", "Model", "Utils/handy_uia_helpers.ahk", "button"),
        e.Call("handy.exe", "Advanced", "Advanced", "Utils/macros_system.ahk", "any"),
        e.Call("handy.exe", "AddWord", "Add a word", "Utils/macros_system.ahk", "edit"),
        e.Call("handy.exe", "History", "History", "Utils/handy_replay_last.ahk", "any"),
        e.Call("handy.exe", "Play", "Play", "Utils/handy_replay_last.ahk", "button"),
        e.Call("handy.exe", "Retranscribe", "Re-transcribe", "Utils/handy_retranscribe_last.ahk", "button"),
        e.Call("handy.exe", "CopyTranscription", "Copy transcription", "Utils/handy_retranscribe_last.ahk", "button"),
        e.Call("Peek", "PageView", "Page view", "Utils/peek_pdf_study_03.ahk", "button"),
        e.Call("Peek", "TwoPage", "Two page", "Utils/peek_pdf_study_03.ahk", "any"),
        e.Call("M365 Copilot", "Stop", "Stop generating", "Shift keys/m365_copilot_temp.ahk", "button"),
        e.Call("M365 Copilot", "Composer", "Message Copilot", "Shift keys/m365_copilot_temp.ahk", "edit"),
        e.Call("M365 Copilot", "Send", "Send", "Shift keys/m365_copilot_temp.ahk", "button"),
    ]
    return rows
}

UiElementCatalog_ForApp(appKey) {
    found := []
    appKey := Trim(appKey)
    if (appKey = "")
        return found
    for entry in UiElementCatalog_All() {
        if (entry.appKey = appKey)
            found.Push(entry)
    }
    return found
}
